spring.kafka.bootstrap-servers=${KAFKA_HOST_NAME}:${KAFKA_PORT}
spring.datasource.url=jdbc:postgresql://${DB_HOST_NAME}:${DB_PORT}/${DB_NAME:notification_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}