spring.profiles.active=${APP_ACTIVE_PROFILE:"none"}
spring.cloud.gcp.credentials.location=firebase-service-account.json
spring.kafka.bootstrap-servers=localhost:9092
spring.datasource.url=jdbc:postgresql://46.101.99.4:15010/notification_db_dev
spring.datasource.username=notification
spring.datasource.password=Password12*
spring.jpa.hibernate.ddl-auto=update

app.feign.auth.url=http://46.101.99.4:5000/api
app.jwt_secret_key=mysecuritykeymysecuritykeymysecuritykeymysecuritykey
