spring.cloud.vault.port=${VAULT_PORT}
spring.cloud.vault.host=${VAULT_HOST}
spring.cloud.vault.scheme=${VAULT_SCHEMA}
spring.cloud.vault.authentication=${VAULT_AUTHENTICATION}
spring.cloud.vault.app-role.role=${VAULT_ROLE}
spring.cloud.vault.app-role.role-id=${VAULT_ROLE_ID}
spring.cloud.vault.app-role.secret-id=${VAULT_SECRET_ID}
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=${VAULT_BACKEND}
spring.cloud.vault.kv.default-context=${VAULT_DEFAULT_CONTEXT}
spring.config.import=vault://

spring.kafka.bootstrap-servers=${KAFKA_HOST_NAME}:${KAFKA_PORT}
spring.datasource.url=jdbc:postgresql://${DB_HOST_NAME}:${DB_PORT}/${DB_NAME:notification_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.feign.auth.url=http://${AUTH_MS_HOST}:${AUTH_MS_PORT}/api
app.jwt_secret_key=${JWT_SECRET_KEY}